artifact_location: file:///C:/Users/roish/Documents/GitHub/final-project-sapir/runs/mlflow/964550983071710640
creation_time: 1778513766337
experiment_id: '964550983071710640'
last_update_time: 1778513766337
lifecycle_stage: active
name: /Shared/Ultralytics
trace_location: null
workspace: default
